### ISSUE TITLE
install VScode

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/APSshare-anaconda-management#4]
@qzhang234 : You requested VScode to be installed in *Python on APSshare*

This issue will track the details and notes of that request.

* https://docs.anaconda.com/anaconda/user-guide/tasks/integration/vscode/
* https://code.visualstudio.com/docs/python/environments

This SO article is not much help, though:

* https://stackoverflow.com/questions/49205467/how-to-install-visual-studio-code-ide-using-anaconda

**Comment by qzhang234** [comment]
Pete:

Thanks!

Just some background info:

1. The reason I’m thinking about installing VS Code (or PyCharm or any other mainstream IDE) is because I thought it would be neat to have the IPython and (advanced) text editing interface in one place;

2. I’ve managed to install VS Code in a Conda VE under qzhang234, but I can’t get pass admin auth when under 8idiuser. Not sure why though.

Thanks,


QZ

________________________________

**Comment by prjemian** [comment]
Yeah.  The problem is that you cannot sudo to root and install anything on APS linux computers.  Users don't get root access permissions.  What I was reading about install VScode suggested to me that it had to be installed in the base environment.  I'm working on updating [Python3 now](https://github.com/BCDA-APS/APSshare-anaconda-issues/issues/3) but it will take longer than expected since I ran into troubles when I tried about two weeks ago.  Might just have to reinstall the whole thing.  Not happy with that.

How did you install VScode into a virtual environment?  Was that using `conda install`?

**Comment by qzhang234** [comment]
Pete:

This is the error I got when I tried to install on 8idiuser. Same thing worked when I install under VE QZ_Py_Test when logged in as qzhang234.

Any suggestions why this might be the case? I thought you can bypass root auth by using VE ...

Thanks,


QZ


________________________________

**Comment by prjemian** [comment]
Can't bypass root auth.  The defense for that is robust.  Did not see the error message?  Can you post it again?

**Comment by qzhang234** [comment]
Here's the error message. Guess the image is not included into the discussion thread when you just reply to the email ...
<img width="664" alt="Screen Shot 2019-09-01 at 1 26 34 AM" src="https://user-images.githubusercontent.com/48140482/64290561-ebe97600-cf2b-11e9-97a8-0a99c3f0532c.png">

**Comment by prjemian** [comment]
Yup.  Need IT to install that for you.  On a per machine basis.  And I'm not sure how well that cooperates with the system python (/usr/bin and /usr/lib).

There *must* be a way to install this with anaconda.  But I *must* put this aside for now to work on https://github.com/BCDA-APS/APSshare-anaconda-issues/issues/3.

**Comment by qzhang234** [comment]
Yes. The whole reason I used VS Code instead of the other zillion IDEs is because I thought it came with anaconda and APS has anaconda. But I agree anaconda3 (namely issue #3) is way, way more important than this. Please feel free to close this issue

**Comment by prjemian** [comment]
Not closing yet, might be able to select VScode during the install process (as the docs suggest).

**Comment by prjemian** [comment]
Just installed a local copy of everything we have on /APSshare/anaconda3/x86_64 (Python3, 64-bit).  Launched anaconda-navigator and pressed the "install" button for VScode.  This screen comes up asking for sysAdmin credentials.
![Clipboard01](https://user-images.githubusercontent.com/2279984/64299097-81d9cc80-cf3d-11e9-816f-263eefcfe8de.jpg)

**Comment by prjemian** [comment]
Summary is: we cannot install VS Code as part of /APSshare python since it requires sysAdmin credentials (and likely installs *only* on the local workstation).

Too bad.
